# Faça um programa que leia um número inteiro qualquer e mostra na tela a sua tabuada

n = int(input("Digite um valor inteiro: "))
print("---------------------------------")
print(f"          Tabuada do {n}          ")
print("---------------------------------")
print("             Adição             ")
print(f"{n} + 1 = {n + 1}")
print(f"{n} + 2 = {n + 2}")
print(f"{n} + 3 = {n + 3}")
print(f"{n} + 4 = {n + 4}")
print(f"{n} + 5 = {n + 5}")
print(f"{n} + 6 = {n + 6}")
print(f"{n} + 7 = {n + 7}")
print(f"{n} + 8 = {n + 8}")
print(f"{n} + 9 = {n + 9}")
print(f"{n} + 10 = {n + 10}")
print("---------------------------------")
print("            Subtração            ")
print(f"{n} - 1 = {n - 1}")
print(f"{n} - 2 = {n - 2}")
print(f"{n} - 3 = {n - 3}")
print(f"{n} - 4 = {n - 4}")
print(f"{n} - 5 = {n - 5}")
print(f"{n} - 6 = {n - 6}")
print(f"{n} - 7 = {n - 7}")
print(f"{n} - 8 = {n - 8}")
print(f"{n} - 9 = {n - 9}")
print(f"{n} - 10 = {n - 10}")
print("---------------------------------")
print("          Multiplicação          ")
print(f"{n} * 1 = {n * 1}")
print(f"{n} * 2 = {n * 2}")
print(f"{n} * 3 = {n * 3}")
print(f"{n} * 4 = {n * 4}")
print(f"{n} * 5 = {n * 5}")
print(f"{n} * 6 = {n * 6}")
print(f"{n} * 7 = {n * 7}")
print(f"{n} * 8 = {n * 8}")
print(f"{n} * 9 = {n * 9}")
print(f"{n} * 10 = {n * 10}")
print("---------------------------------")
print("             Divisão             ")
print(f"{n} / 1 = {n / 1}")
print(f"{n} / 2 = {n / 2}")
print(f"{n} / 3 = {n / 3}")
print(f"{n} / 4 = {n / 4}")
print(f"{n} / 5 = {n / 5}")
print(f"{n} / 6 = {n / 6}")
print(f"{n} / 7 = {n / 7}")
print(f"{n} / 8 = {n / 8}")
print(f"{n} / 9 = {n / 9}")
print(f"{n} / 10 = {n / 10}")
print("---------------------------------")